{
  "hash": "8c1473268c6755950cc3222046032295",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Predictive Policing - Technical Implementation\"\nsubtitle: \"MUSA 5080 - Fall 2025\"\nauthor: \"Chloe Robinson\"\ndate: today\nformat:\n  html:\n    code-fold: show\n    code-tools: true\n    toc: true\n    toc-depth: 3\n    toc-location: left\n    theme: cosmo\n    embed-resources: true\neditor: visual\nexecute:\n  warning: false\n  message: false\n---\n\n## About This Exercise\n\nSpatial predictive model for burglaries using count regression and spatial features.\n\n# Setup\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Load required packages\nlibrary(tidyverse)      # Data manipulation\nlibrary(sf)             # Spatial operations\nlibrary(here)           # Relative file paths\nlibrary(viridis)        # Color scales\nlibrary(terra)          # Raster operations (replaces 'raster')\nlibrary(spdep)          # Spatial dependence\nlibrary(FNN)            # Fast nearest neighbors\nlibrary(MASS)           # Negative binomial regression\nlibrary(patchwork)      # Plot composition (replaces grid/gridExtra)\nlibrary(knitr)          # Tables\nlibrary(kableExtra)     # Table formatting\nlibrary(classInt)       # Classification intervals\nlibrary(here)\nlibrary(broom) \n\n# Spatstat split into sub-packages\nlibrary(spatstat.geom)    # Spatial geometries\nlibrary(spatstat.explore) # Spatial exploration/KDE\n\n# Set options\noptions(scipen = 999)  # No scientific notation\nset.seed(5080)         # Reproducibility\n\n# Create consistent theme for visualizations\ntheme_crime <- function(base_size = 11) {\n  theme_minimal(base_size = base_size) +\n    theme(\n      plot.title = element_text(face = \"bold\", size = base_size + 1),\n      plot.subtitle = element_text(color = \"gray30\", size = base_size - 1),\n      legend.position = \"right\",\n      panel.grid.minor = element_blank(),\n      axis.text = element_blank(),\n      axis.title = element_blank()\n    )\n}\n\n# Set as default\ntheme_set(theme_crime())\n```\n:::\n\n\n# Part 1: Load and Explore Data\n\n## Exercise 1.1: Load Chicago Spatial Data\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Load police districts (used for spatial cross-validation)\npoliceDistricts <- \n  st_read(\"https://data.cityofchicago.org/api/geospatial/24zt-jpfn?method=export&format=GeoJSON\") %>%\n  st_transform('ESRI:102271') %>%\n  dplyr::select(District = dist_num)\n\n# Load police beats (smaller administrative units)\npoliceBeats <- \n  st_read(\"https://data.cityofchicago.org/api/geospatial/n9it-hstw?method=export&format=GeoJSON\") %>%\n  st_transform('ESRI:102271') %>%\n  dplyr::select(Beat = beat_num)\n\n# Load Chicago boundary\nchicagoBoundary <- \n  st_read(\"https://raw.githubusercontent.com/urbanSpatial/Public-Policy-Analytics-Landing/master/DATA/Chapter5/chicagoBoundary.geojson\") %>%\n  st_transform('ESRI:102271')\n```\n:::\n\n\n## Exercise 1.2: Load Burglary Data\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Load from provided data file (downloaded from Chicago open data portal)\nburglaries <- st_read(\"data/burglaries.shp\") %>%\n  st_transform(\"ESRI:102271\")\n\n# Check the data\ncat(\"\\n✓ Loaded burglary data\\n\")\ncat(\"  - Number of burglaries:\", nrow(burglaries), \"\\n\")\ncat(\"  - CRS:\", st_crs(burglaries)$input, \"\\n\")\ncat(\"  - Date range:\", min(burglaries$date, na.rm = TRUE), \"to\", \n    max(burglaries$date, na.rm = TRUE), \"\\n\")\n```\n:::\n\n\n**Question 1.1:** How many burglaries are in the dataset? What time period does this cover? Why does the coordinate reference system matter for our spatial analysis?\n\nThere were 7,482 burglaries reported in Chicago in 2017. The coordinate reference system used for this spatial analysis is ESRI:102271 (Illinois State Plane East, NAD83, US Feet). This is the appropriate coordinate reference system for Chicago, as it is designed specifically for the Illinois East region, so spatial distortion is minimized, and the unit of measurment is US survey feet, the most common unit in US planning and engineering. It also uses a projected coordinate system, allowing for accurate distance and area calculations - which the longitude/latitude CRS can't do reliably. Using this CRS ensures that the results for the spatial operations conducted on burglaries in Chicago are reliable and interpenetrate.\n\n## Exercise 1.3: Visualize Point Data\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Visualise Burglaries \n# Simple point map\np1 <- ggplot() + \n  geom_sf(data = chicagoBoundary, fill = \"gray95\", color = \"gray60\") +\n  geom_sf(data = burglaries, color = \"#d62828\", size = 0.1, alpha = 0.4) +\n  labs(\n    title = \"Burglary Locations\",\n    subtitle = paste0(\"Chicago 2017, n = \", nrow(burglaries))\n  )\n\n# Density surface using modern syntax\np2 <- ggplot() + \n  geom_sf(data = chicagoBoundary, fill = \"gray95\", color = \"gray60\") +\n  geom_density_2d_filled(\n    data = data.frame(st_coordinates(burglaries)),\n    aes(X, Y),\n    alpha = 0.7,\n    bins = 8\n  ) +\n  scale_fill_viridis_d(\n    option = \"plasma\",\n    direction = -1,\n    guide = \"none\"  # Modern ggplot2 syntax (not guide = FALSE)\n  ) +\n  labs(\n    title = \"Density Surface\",\n    subtitle = \"Kernel density estimation\"\n  )\n\n# Combine plots using patchwork (modern approach)\np1 + p2 + \n  plot_annotation(\n    title = \"Spatial Distribution of Burglaries in Chicago\",\n    tag_levels = 'A'\n  )\n```\n\n::: {.cell-output-display}\n![](Lab3_new_files/figure-html/visualize-points-1.png){width=960}\n:::\n:::\n\n\n**Question 1.2:** What spatial patterns do you observe? Are burglaries evenly distributed across Chicago? Where are the highest concentrations? What might explain these patterns?\n\nSeveral factors likely contribute to this uneven distribution. Neighborhoods with higher population and housing density naturally create more opportunities for burglary compared to areas with fewer homes. Mixed-use or commercial corridors with steady foot traffic may also attract offenders. Socioeconomic conditions also play a role, areas facing economic disadvantage often see higher crime, while wealthier neighborhoods can become targets because of the higher value of property. Historical policing patterns may also influence where incidents are reported or detected, shaping how the patterns are on the map.\n\n# Part 2: Create Fishnet Grid\n\n## Exercise 2.1: Understanding the Fishnet\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create 500m x 500m grid\nfishnet <- st_make_grid(\n  chicagoBoundary,\n  cellsize = 500,  # 500 meters per cell\n  square = TRUE\n) %>%\n  st_sf() %>%\n  mutate(uniqueID = row_number())\n\n# Keep only cells that intersect Chicago\nfishnet <- fishnet[chicagoBoundary, ]\n```\n:::\n\n\n**Question 2.1:** Why do we use a regular grid instead of existing boundaries like neighborhoods or census tracts? What are the advantages and disadvantages of this approach?\n\nA regular fishnet grid was generated across the Chicago boundary with 500 × 500 meter cells, producing 2,458 cells in total, each covering approximately 250,000 m² (0.25 km²). Only cells that intersect the city boundary were retained, ensuring that all grid squares fall within Chicago. A fishnet grid is used to provide a uniform spatial framework, avoiding the inconsistencies of boundaries such as neighborhoods or census tracts. Using grids makes it easier to compare different areas evenly as it uses equal-sized spatial units. However, this approach does have limitations. Grids can split local areas or include cells that cover uninhabited zones like water, parks or industrial areas. Despite the limitations, the fishnet grid is valuable for data-driven spatial modelling, as it reduces bias due to predefined administrative boundaries.\n\n## Exercise 2.2: Aggregate Burglaries to Grid\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Spatial join: which cell contains each burglary?\nburglaries_fishnet <- st_join(burglaries, fishnet, join = st_within) %>%\n  st_drop_geometry() %>%\n  group_by(uniqueID) %>%\n  summarize(countBurglaries = n())\n\n# Join back to fishnet (cells with 0 burglaries will be NA)\nfishnet <- fishnet %>%\n  left_join(burglaries_fishnet, by = \"uniqueID\") %>%\n  mutate(countBurglaries = replace_na(countBurglaries, 0))\n\n# Summary statistics\nsummary(fishnet$countBurglaries)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n  0.000   0.000   2.000   3.042   5.000  40.000 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"\\nCells with zero burglaries:\", \n    sum(fishnet$countBurglaries == 0), \n    \"/\", nrow(fishnet),\n    \"(\", round(100 * sum(fishnet$countBurglaries == 0) / nrow(fishnet), 1), \"%)\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCells with zero burglaries: 781 / 2458 ( 31.8 %)\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Visualize aggregated counts\nggplot() +\n  geom_sf(data = fishnet, aes(fill = countBurglaries), color = NA) +\n  geom_sf(data = chicagoBoundary, fill = NA, color = \"white\", linewidth = 1) +\n  scale_fill_viridis_c(\n    name = \"Burglaries\",\n    option = \"plasma\",\n    trans = \"sqrt\",  # Square root for better visualization of skewed data\n    breaks = c(0, 1, 5, 10, 20, 40)\n  ) +\n  labs(\n    title = \"Burglary Counts by Grid Cell\",\n    subtitle = \"500m x 500m cells, Chicago 2017\"\n  ) +\n  theme_crime()\n```\n\n::: {.cell-output-display}\n![](Lab3_new_files/figure-html/visualize-fishnet-1.png){width=768}\n:::\n:::\n\n\n**Question 2.2:** What is the distribution of burglary counts across cells? Why do so many cells have zero burglaries? Is this distribution suitable for count regression? (Hint: look up overdispersion)\n\nAfter aggregating burglaries to the 500m × 500m fishnet grid, there was a clear variation in how crime was distributed across the city. The burglary counts across the grid are uneven. The majority of the cells have very few or zero burglaries. Burglary counts ranged from 0 to 40 per cell, with a mean of 3.52. About 24% of all grid cells recorded zero burglaries, showing that many parts of the city experience little or no burglary activity in 2017. The much higher maximum value shows that burglaries are not evenly spread out as there are clear distinct hotspot areas where incidents are concentrated. This pattern reflects the typical clustering seen in crime data, where a small number of places account for a large share of events. This distribution is suitable for count regression, but it is likely overdispersed, meaning that the varience is larger than the mean. Overdispersion is common in spatial crime data because counts cluster in certain locations rather than being evenly distributed.\n\n# Part 3: Create a Kernel Density Baseline\n\nBefore building complex models, let's create a simple baseline using **Kernel Density Estimation (KDE)**.\n\n**The KDE baseline asks:** \"What if crime just happens where it happened before?\"\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Convert burglaries to ppp (point pattern) format for spatstat\nburglaries_ppp <- as.ppp(\n  st_coordinates(burglaries),\n  W = as.owin(st_bbox(chicagoBoundary))\n)\n\n# Calculate KDE with 1km bandwidth\nkde_burglaries <- density.ppp(\n  burglaries_ppp,\n  sigma = 1000,  # 1km bandwidth\n  edge = TRUE    # Edge correction\n)\n\n# Convert to terra raster (modern approach, not raster::raster)\nkde_raster <- rast(kde_burglaries)\n\n# Extract KDE values to fishnet cells\nfishnet <- fishnet %>%\n  mutate(\n    kde_value = terra::extract(\n      kde_raster,\n      vect(fishnet),\n      fun = mean,\n      na.rm = TRUE\n    )[, 2]  # Extract just the values column\n  )\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Plot\nggplot() +\n  geom_sf(data = fishnet, aes(fill = kde_value), color = NA) +\n  geom_sf(data = chicagoBoundary, fill = NA, color = \"white\", linewidth = 1) +\n  scale_fill_viridis_c(\n    name = \"KDE Value\",\n    option = \"plasma\"\n  ) +\n  labs(\n    title = \"Kernel Density Estimation Baseline\",\n    subtitle = \"Simple spatial smoothing of burglary locations\"\n  ) +\n  theme_crime()\n```\n\n::: {.cell-output-display}\n![](Lab3_new_files/figure-html/visualize-kde-1.png){width=768}\n:::\n:::\n\n\n**Question 3.1:** How does the KDE map compare to the count map? What does KDE capture well? What does it miss?\n\nThe KDE represents our null hypothesis that burglaries happen where they happened before, with no other information. The KDE map gives a smoother visual of burglary patterns than the raw count map, clearly highlighting the major hot-spot areas and shows broader clusters across the city. However, KDE also loses some important detail. It can blur sharp boundaries and local spikes in burglaries that the count map can show more accurately and precisely. Small but intense hotspots may appear diluted, and areas with no burglaries can still show some density simply because they sit near busier cells. KDE is useful for understanding larger, regional patterns, but not as accurate at pinpointing exact locations on a smaller scale.\n\n# Part 4: Create Spatial Predictor Variables\n\nNow we'll create features that might help predict burglaries. We'll use \"broken windows theory\" logic: signs of disorder predict crime.\n\n## Exercise 4.1: Load 311 Graffiti Removal Calls\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Graffiti Removal Requests \ngraffiti <- st_read(\n  \"https://data.cityofchicago.org/api/geospatial/hec5-y4x5?method=export&format=GeoJSON\"\n) %>%\n  st_transform('ESRI:102271')\n\ngraffiti_with_units <- graffiti %>%\n  st_join(policeDistricts, join = st_within) %>%\n  st_join(policeBeats, join = st_within) %>%\n  filter(st_is_valid(geometry)) %>%\n  filter(!st_is_empty(geometry))\n```\n:::\n\n\n## Exercise 4.2: Count of Graffiti Calls per Cell\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Aggregate graffiti calls to fishnet\ngraffiti_fishnet <- st_join(graffiti_with_units, fishnet, join = st_within) %>%\n  st_drop_geometry() %>%\n  group_by(uniqueID) %>%\n  summarize(graffiti_n = n())   # <-- use a different name here\n\ncat(\"Rows in graffiti_fishnet:\", nrow(graffiti_fishnet), \"\\n\")\ncat(\"Unique cells with any graffiti:\", length(unique(graffiti_fishnet$uniqueID)), \"\\n\")\n\n# Join counts back to fishnet\nfishnet <- fishnet %>%\n  left_join(graffiti_fishnet, by = \"uniqueID\")\n\n# Replace NAs with 0 (do it outside mutate to avoid masking issues)\nfishnet$graffiti_n[is.na(fishnet$graffiti_n)] <- 0\n\nsummary(fishnet$graffiti_n)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\np1 <- ggplot() +\n  geom_sf(data = fishnet, aes(fill = graffiti_n), color = NA) +\n  scale_fill_viridis_c(name = \"Count\", option = \"magma\") +\n  labs(title = \"Graffiti Removal 311 Calls\") +\n  theme_crime()\n\np2 <- ggplot() +\n  geom_sf(data = fishnet, aes(fill = countBurglaries), color = NA) +\n  scale_fill_viridis_c(name = \"Count\", option = \"plasma\") +\n  labs(title = \"Burglaries\") +\n  theme_crime()\n\np1 + p2 +\n  plot_annotation(title = \"Are graffiti calls and burglaries correlated?\")\n```\n\n::: {.cell-output-display}\n![](Lab3_new_files/figure-html/visualize-graffiti-1.png){width=672}\n:::\n:::\n\n\n**Question 4.1:** Do you see a visual relationship between graffiti and burglaries? What does this suggest?\n\nThere is a small visual overlap between the two maps, with some areas with higher graffiti calls also showing more burglaries, but the patterns are not identical. The graffiti map shows strong clusters, but they depend heavily on who actually reports graffiti issues to 311. Some neighborhoods may know more about 311 calls than others, trust city service employees more, and expect a response tend to report more than those that don't. This means that neighborhoods with high volumes of graffiti 311 calls don't necessarily have the highest volume of graffiti, it just means they have the highest number of people reporting it. The burglary patterns reflects where crimes actually happened, not just where they were reported, showing that burglaries tend to happen based on opportunity, foot traffic, housing density, and policing - not who decides to make a call to 311. The graffiti map shows crime and differences in civil engagement across neighborhoods, while the burglary map reflects crime patterns more accurately. Because of this difference, graffiti calls to 311 alone should not be treated as an accurate measure of crime without considering who reports and who does not report.\n\n## Exercise 4.3: Nearest Neighbor Features\n\nCount in a cell is one measure. Distance to the nearest 3 abandoned cars captures local context.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Get coordinates for cell centroids and graffiti points\nfishnet_coords <- st_coordinates(st_centroid(fishnet))\ngraffiti_coords <- st_coordinates(graffiti_with_units)\n\n# Calculate k nearest neighbors and distances (k = 3)\nnn_result <- get.knnx(graffiti_coords, fishnet_coords, k = 3)\n\n# Add mean distance to 3 nearest graffiti calls to fishnet\nfishnet <- fishnet %>%\n  mutate(\n    graffiti_with_units.nn = rowMeans(nn_result$nn.dist)\n  )\n\nsummary(fishnet$graffiti_with_units.nn)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     Min.   1st Qu.    Median      Mean   3rd Qu.      Max. \n   0.5533   28.6074   60.2756  135.1374  137.9480 1476.2625 \n```\n\n\n:::\n:::\n\n\n**Question 4.2:** What does a low value of `graffiti_with_units.nn` mean? A high value? Why might this be informative?\n\nA low K Nearest Neighbors (KNN) value means the cell is very close to recent graffiti, and a high KNN value means the nearest graffiti is far away, showing how close each area is to graffiti activity. The average distance from each grid cell to its three nearest graffiti incidents is about 109 meters, with distances ranging from roughly half a meter to about 1.45 kilometers. This means some parts of the city are right next to graffiti activity, while others are much farther away. These distances help show how closely each area is situated to places where graffiti regularly occurs.\n\n## Exercise 4.4: Distance to Hot Spots\n\nLet's identify clusters of graffiti calls using Local Moran's I, then calculate distance to these hot spots.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Function to calculate Local Moran's I\ncalculate_local_morans <- function(data, variable, k = 5) {\n\n  # Use a clean numeric vector (no NAs)\n  x <- data[[variable]]\n  x[is.na(x)] <- 0\n\n  # Create spatial weights based on k-nearest neighbors\n  coords <- st_coordinates(st_centroid(data))\n  neighbors <- knn2nb(knearneigh(coords, k = k))\n  weights <- nb2listw(neighbors, style = \"W\", zero.policy = TRUE)\n\n  # Local Moran's I\n  local_moran <- localmoran(x, weights)\n\n  mean_val <- mean(x, na.rm = TRUE)\n\n  data %>%\n    mutate(\n      local_i       = local_moran[, 1],\n      p_value       = local_moran[, 5],\n      is_significant = p_value < 0.05,\n      moran_class   = case_when(\n        !is_significant ~ \"Not Significant\",\n        local_i > 0 & .data[[variable]] >  mean_val ~ \"High-High\",\n        local_i > 0 & .data[[variable]] <= mean_val ~ \"Low-Low\",\n        local_i < 0 & .data[[variable]] >  mean_val ~ \"High-Low\",\n        local_i < 0 & .data[[variable]] <= mean_val ~ \"Low-High\",\n        TRUE ~ \"Not Significant\"\n      )\n    )\n}\n\n# Apply to graffiti counts\nfishnet <- calculate_local_morans(fishnet, \"graffiti_n\", k = 5)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Visualize hot spots\nggplot() +\n  geom_sf(data = fishnet, aes(fill = moran_class), color = NA) +\n  scale_fill_manual(\n    values = c(\n      \"High-High\"      = \"#d7191c\",\n      \"High-Low\"       = \"#fdae61\",\n      \"Low-High\"       = \"#abd9e9\",\n      \"Low-Low\"        = \"#2c7bb6\",\n      \"Not Significant\" = \"gray90\"\n    ),\n    name = \"Cluster Type\"\n  ) +\n  labs(\n    title = \"Local Moran's I: Graffiti Clusters\",\n    subtitle = \"High-High = Hot spots of disorder\"\n  ) +\n  theme_crime()\n```\n\n::: {.cell-output-display}\n![](Lab3_new_files/figure-html/visualize-morans-1.png){width=768}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Get centroids of \"High-High\" cells (hot spots)\nhotspots <- fishnet %>%\n  filter(moran_class == \"High-High\") %>%\n  st_centroid()\n\nif (nrow(hotspots) > 0) {\n\n  fishnet <- fishnet %>%\n    mutate(\n      dist_to_hotspot = as.numeric(\n        st_distance(st_centroid(fishnet), hotspots %>% st_union())\n      )\n    )\n\n  cat(\"  - Number of hot spot cells:\", nrow(hotspots), \"\\n\")\n\n} else {\n\n  fishnet <- fishnet %>%\n    mutate(dist_to_hotspot = 0)\n\n}\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  - Number of hot spot cells: 318 \n```\n\n\n:::\n:::\n\n\n**Question 4.3:** Why might distance to a cluster of abandoned cars be more informative than distance to a graffiti call? What does Local Moran's I tell us?\n\nA Local Moran’s I statistic was used to identify spatial clusters of graffiti activity across Chicago. Local Moran's I does not measure the distance to individual graffiti calls like the KNN does, but instead examines how similar each cell is to it's neighbor. Using five nearest neighbors, the analysis identified 255 \"high-high\" hot-spot cells, meaning these grid cells have high graffiti counts and are surrounded by other high-count cells. These represent the strongest concentrations of graffiti activity in the city. Only a small number of \"low-high\" outliers appeared, cells with low graffiti counts located next to areas of high activity. Overall, the results show that graffiti is not evenly spread out. Instead, it forms district clusters and hot-spots, indicating concentrated graffiti activity rather than random distribution.\n\n------------------------------------------------------------------------\n\n# Part 5: Join Police Districts for Cross-Validation\n\nWe'll use police districts for our spatial cross-validation.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Join district information to fishnet\n# Make sure policeDistricts has a 'District' column\nif (!\"District\" %in% names(policeDistricts)) {\n  policeDistricts <- policeDistricts %>%\n    dplyr::rename(District = dist_num)\n}\n\n# Join district information to fishnet\nfishnet <- st_join(\n  fishnet,\n  policeDistricts,\n  join = st_within,\n  left = TRUE\n)\n\n# Drop cells outside any district\nfishnet <- fishnet %>%\n  filter(!is.na(District))\n\n# Now create modeling data\nfishnet_model <- fishnet %>%\n  st_drop_geometry() %>%\n  dplyr::select(\n    uniqueID,\n    District,\n    countBurglaries,\n    graffiti_n,              \n    graffiti_with_units.nn,\n    dist_to_hotspot\n  ) %>%\n  na.omit()\n\nsummary_table <- tibble(\n  total_cells             = nrow(fishnet),\n  zero_burglary_cells     = sum(fishnet$countBurglaries == 0),\n  percent_zero            = round(mean(fishnet$countBurglaries == 0) * 100, 1),\n  num_districts           = length(unique(fishnet$District)),\n  model_observations      = nrow(fishnet_model),\n  model_variables         = ncol(fishnet_model)\n)\n\nknitr::kable(summary_table, caption = \"Summary of Data Preparation\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Summary of Data Preparation\n\n| total_cells| zero_burglary_cells| percent_zero| num_districts| model_observations| model_variables|\n|-----------:|-------------------:|------------:|-------------:|------------------:|---------------:|\n|        1708|                 413|         24.2|            22|               1708|               6|\n\n\n:::\n:::\n\n\n# Part 6: Model Fitting\n\n## Exercise 6.1: Poisson Regression\n\nBurglary counts are count data (0, 1, 2, 3...). We'll use **Poisson regression**.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Fit Poisson regression\nmodel_poisson <- glm(\n  countBurglaries ~ graffiti_n + graffiti_with_units.nn + dist_to_hotspot,\n  data  = fishnet_model,\n  family = \"poisson\"\n)\n\nmodel_summary <- broom::tidy(model_poisson) %>%\n  mutate(across(where(is.numeric), ~ round(., 4)))\n\nknitr::kable(\n  model_summary,\n  caption = \"Poisson Regression Model Summary\"\n)\n```\n:::\n\n\n**Question 6.1:** Interpret the coefficients. Which variables are significant? What do the signs (positive/negative) tell you?\n\nThe model shows that all three predictors are statistically significant. The coefficient for graffiti_n is 0.000072, meaning that as the number of graffiti calls in a cell increases, burglary counts increase slightly. The dist_to_hotspot variable has a small positive coefficient of 0.000012, meaning burglary counts rise slightly as a cell gets farther from major graffiti clusters. The coefficient for graffiti_with_units.nn is –0.00633, so cells that are closer to recent graffiti incidents (with a lower KNN distance) tend to have more burglaries; the negative sign reflects that shorter distances correspond to higher risk. Overall, the results suggest that immediate, local graffiti activity is more closely related to burglary patterns than overall distance to broader graffiti hot-spots.\n\n## Exercise 6.2: Check for Overdispersion\n\nPoisson regression assumes mean = variance. Real count data often violates this (overdispersion).\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Calculate dispersion parameter\ndispersion <- sum(residuals(model_poisson, type = \"pearson\")^2) /\n              model_poisson$df.residual\n\ntibble(\n  dispersion = round(dispersion, 2),\n  overdispersed = ifelse(dispersion > 1.5, \"Yes (use Negative Binomial)\", \"No (Poisson OK)\")\n) |>\n  knitr::kable(caption = \"Overdispersion Check\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Overdispersion Check\n\n| dispersion|overdispersed               |\n|----------:|:---------------------------|\n|       3.61|Yes (use Negative Binomial) |\n\n\n:::\n:::\n\n\n## Exercise 6.3: Negative Binomial Regression\n\nIf overdispersed, use **Negative Binomial regression** (more flexible).\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Fit Negative Binomial model\nmodel_nb <- glm.nb(\n  countBurglaries ~ graffiti_n + graffiti_with_units.nn + dist_to_hotspot,\n  data = fishnet_model\n)\n\n# Save AIC\nnb_aic <- AIC(model_nb)\n\n# Create a clean coefficient table\ntidy(model_nb) |>\n  mutate(\n    estimate  = round(estimate, 4),\n    std.error = round(std.error, 4),\n    statistic = round(statistic, 2),\n    p.value   = round(p.value, 4)\n  ) |>\n  kable(caption = \"Negative Binomial Regression Coefficients\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Negative Binomial Regression Coefficients\n\n|term                   | estimate| std.error| statistic| p.value|\n|:----------------------|--------:|---------:|---------:|-------:|\n|(Intercept)            |   1.6604|    0.0497|     33.38|  0.0000|\n|graffiti_n             |   0.0001|    0.0000|      1.55|  0.1210|\n|graffiti_with_units.nn |  -0.0079|    0.0005|    -17.15|  0.0000|\n|dist_to_hotspot        |   0.0000|    0.0000|      3.34|  0.0008|\n\n\n:::\n\n```{.r .cell-code}\ncomparison <- tibble(\n  Model = c(\"Poisson\", \"Negative Binomial\"),\n  AIC   = c(AIC(model_poisson), AIC(model_nb))\n) |>\n  mutate(AIC = round(AIC, 1))\n\nkable(comparison, caption = \"Model Comparison by AIC\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Model Comparison by AIC\n\n|Model             |    AIC|\n|:-----------------|------:|\n|Poisson           | 9456.1|\n|Negative Binomial | 7654.1|\n\n\n:::\n:::\n\n\n**Question 6.2:** Which model fits better (lower AIC)? What does this tell you about the data?\n\nAIC (Akaike Information Criterion) is a common measure used to compare statistical models, it evaluates model quality, and a lower AIC value indicates a better-fitting, more efficient model. Here, we are comparing the Poisson Regression Model to the Negative Binomial Regression Model, using the same predicton.\n\nThe Negative Binomial model fits the data much better than the Poisson model because it has a much lower AIC value (7654.1 compared to 9456.1). This large difference indicates that the Poisson model is not suitable for the data. The dispersion parameter was estimated at 3.61, which is far above the rule-of-thumb cutoff of 1.5 and shows strong overdispersion in the burglary counts. Because the Poisson model assumes that the mean and variance are equal, it cannot handle this extra variability. The Negative Binomial model includes an additional parameter to model that extra variance, which is why its AIC is much lower and why it provides a more reliable fit for the burglary data.\n\n# Part 7: Spatial Cross-Validation\n\nStandard cross-validation randomly splits data. But with spatial data, this means training on cells right next to test cells (information leakage!).\n\n**Leave-One-Group-Out (LOGO) Cross-Validation** trains on all districts except one, then tests on the held-out district.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\n# Get unique districts\ndistricts   <- unique(fishnet_model$District)\ncv_results  <- tibble()\n\n\nfor (i in seq_along(districts)) {\n  \n  test_district <- districts[i]\n  \n  train_data <- fishnet_model %>% filter(District != test_district)\n  test_data  <- fishnet_model %>% filter(District == test_district)\n  \n model_cv <- glm.nb(\n  countBurglaries ~ graffiti_n + graffiti_with_units.nn + dist_to_hotspot,\n  data = train_data\n)\n  \n  test_data <- test_data %>%\n    mutate(\n      prediction = predict(model_cv, newdata = test_data, type = \"response\")\n    )\n  \n  mae  <- mean(abs(test_data$countBurglaries - test_data$prediction))\n  rmse <- sqrt(mean((test_data$countBurglaries - test_data$prediction)^2))\n  \n  \nmean_mae  <- round(mean(cv_results$mae), 2)\nmean_rmse <- round(mean(cv_results$rmse), 2)\n\ntibble(\n  Metric = c(\"Mean MAE\", \"Mean RMSE\"),\n  Value  = c(mean_mae, mean_rmse)\n) %>%\n  kable(\n    caption = \"Cross-Validation Error Summary\",\n    digits = 2\n  ) %>%\n  kable_styling(bootstrap_options = c(\"striped\", \"hover\"))\n  \n  cv_results <- bind_rows(\n    cv_results,\n    tibble(\n      fold         = i,\n      test_district = test_district,\n      n_test       = nrow(test_data),\n      mae          = mae,\n      rmse         = rmse\n    )\n  )\n}\ncv_results %>%\n  arrange(desc(mae)) %>%\n  kable(\n    digits  = 2,\n    caption = \"LOGO CV Results by District\"\n  ) %>%\n  kable_styling(bootstrap_options = c(\"striped\", \"hover\"))\n```\n:::\n\n\n**Question 7.1:** Why is spatial CV more appropriate than random CV for this problem? Which districts were hardest to predict?\n\nSpatial cross-validation is more appropriate than random CV because crime data is spatially clustered, meaning nearby cells tend to share similar burglary and graffiti patterns. If the data were split randomly, many training cells would be located right next to test cells, allowing information to leak across space and making the model appear more accurate than it really is. Holding out an entire district at a time avoids this problem by forcing the model to predict in areas it has not seen before. Based on the results, District 3 (fold 7) was the hardest to predict, with the highest errors, including a MAE of about 6.31 and an RMSE of about 8.42. This suggests that District 3 behaves differently from the rest of the city. Areas such as District 19 and District 22 were among the easiest to predict, with much lower error values.\n\nThe model only predicts well in areas that are already heavily policed, meaning it is learning policing patterns rather than true crime patterns. This limits its usefulness because it will reinforce existing biases and fail to generalize to areas with less police presence or reporting.\n\n# Part 8: Model Predictions and Comparison\n\n## Exercise 8.1: Generate Final Predictions\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Fit final model on all data\nfinal_model <- glm.nb(\n  countBurglaries ~ graffiti_n + graffiti_with_units.nn + dist_to_hotspot,\n  data = fishnet_model\n)\n\nfishnet <- fishnet %>%\n  mutate(\n    prediction_nb = predict(\n      final_model,\n      newdata = fishnet_model,\n      type = \"response\"\n    )[match(uniqueID, fishnet_model$uniqueID)]\n  )\n\nkde_sum   <- sum(fishnet$kde_value,        na.rm = TRUE)\ncount_sum <- sum(fishnet$countBurglaries,  na.rm = TRUE)\n\nfishnet <- fishnet %>%\n  mutate(\n    prediction_kde = (kde_value / kde_sum) * count_sum\n  )\n```\n:::\n\n\n## Exercise 8.2: Compare Model vs. KDE Baseline\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create three maps\n#| fig-width: 12\n#| fig-height: 4\n\np1 <- ggplot() +\n  geom_sf(data = fishnet, aes(fill = countBurglaries), color = NA) +\n  scale_fill_viridis_c(name = \"Count\", option = \"plasma\", limits = c(0, 15)) +\n  labs(title = \"Actual Burglaries\") +\n  theme_crime()\n\np2 <- ggplot() +\n  geom_sf(data = fishnet, aes(fill = prediction_nb), color = NA) +\n  scale_fill_viridis_c(name = \"Predicted\", option = \"plasma\", limits = c(0, 15)) +\n  labs(title = \"Model Predictions (Neg. Binomial)\") +\n  theme_crime()\n\np3 <- ggplot() +\n  geom_sf(data = fishnet, aes(fill = prediction_kde), color = NA) +\n  scale_fill_viridis_c(name = \"Predicted\", option = \"plasma\", limits = c(0, 15)) +\n  labs(title = \"KDE Baseline Predictions\") +\n  theme_crime()\n\np1 + p2 + p3 +\n  plot_annotation(\n    title    = \"Actual vs. Predicted Burglaries\",\n    subtitle = \"Does our complex model outperform simple KDE?\"\n  )\n```\n\n::: {.cell-output-display}\n![](Lab3_new_files/figure-html/compare-models-1.png){width=1152}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Calculate performance metrics\ncomparison <- fishnet %>%\n  st_drop_geometry() %>%\n  filter(!is.na(prediction_nb), !is.na(prediction_kde)) %>%\n  summarize(\n    model_mae  = mean(abs(countBurglaries - prediction_nb)),\n    model_rmse = sqrt(mean((countBurglaries - prediction_nb)^2)),\n    kde_mae    = mean(abs(countBurglaries - prediction_kde)),\n    kde_rmse   = sqrt(mean((countBurglaries - prediction_kde)^2))\n  )\n\ncomparison %>%\n  pivot_longer(everything(), names_to = \"metric\", values_to = \"value\") %>%\n  separate(metric, into = c(\"approach\", \"metric\"), sep = \"_\") %>%\n  pivot_wider(names_from = metric, values_from = value) %>%\n  kable(\n    digits  = 2,\n    caption = \"Model Performance Comparison\"\n  ) %>%\n  kable_styling(bootstrap_options = c(\"striped\", \"hover\"))\n```\n\n::: {.cell-output-display}\n`````{=html}\n<table class=\"table table-striped table-hover\" style=\"margin-left: auto; margin-right: auto;\">\n<caption>Model Performance Comparison</caption>\n <thead>\n  <tr>\n   <th style=\"text-align:left;\"> approach </th>\n   <th style=\"text-align:right;\"> mae </th>\n   <th style=\"text-align:right;\"> rmse </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:left;\"> model </td>\n   <td style=\"text-align:right;\"> 2.56 </td>\n   <td style=\"text-align:right;\"> 3.66 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> kde </td>\n   <td style=\"text-align:right;\"> 2.06 </td>\n   <td style=\"text-align:right;\"> 2.95 </td>\n  </tr>\n</tbody>\n</table>\n\n`````\n:::\n:::\n\n\n**Question 8.1:** Does the complex model outperform the simple KDE baseline? By how much? Is the added complexity worth it?\n\nThe complex model does not outperform the simple KDE baseline. The KDEpredicts burglaries more accurately, with a lower MAE (2.06 vs. 2.56), and a lower RMSE (2.95 vs. 3.66). This means the KDE is consistently closer to the true burglary counts and makes a smaller amount of large errors. Because the KDE is more simple and more accurate, the added complexity of the regression model is not worth it because the baseline model already captures the main spatial pattern better than the more complicated approach.\n\n## Exercise 9.3: Where Does the Model Work Well?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfishnet <- fishnet %>%\n  mutate(\n    error_nb      = countBurglaries - prediction_nb,\n    error_kde     = countBurglaries - prediction_kde,\n    abs_error_nb  = abs(error_nb),\n    abs_error_kde = abs(error_kde)\n  )\n\np1 <- ggplot() +\n  geom_sf(data = fishnet, aes(fill = error_nb), color = NA) +\n  scale_fill_gradient2(\n    name     = \"Error\",\n    low      = \"#2166ac\",\n    mid      = \"white\",\n    high     = \"#b2182b\",\n    midpoint = 0,\n    limits   = c(-10, 10)\n  ) +\n  labs(title = \"Model Errors (Actual - Predicted)\") +\n  theme_crime()\n\np2 <- ggplot() +\n  geom_sf(data = fishnet, aes(fill = abs_error_nb), color = NA) +\n  scale_fill_viridis_c(name = \"Abs. Error\", option = \"magma\") +\n  labs(title = \"Absolute Model Errors\") +\n  theme_crime()\n\np1 + p2\n```\n\n::: {.cell-output-display}\n![](Lab3_new_files/figure-html/prediction-errors-1.png){width=960}\n:::\n:::\n\n\n**Question 9.2:** Where does the model make the biggest errors? Are there spatial patterns in the errors? What might this reveal?\n\nThe final Negative Binomial model shows that only the KNN graffiti distance and the distance to the hot-spot are meaningful predictors of burglary. The KNN variable (rate ratio 0.992) is strongly significant, meaning burglaries are more likely in places that are very close to recent graffiti incidents. Distance to the larger hot-spot is also significant, but the effect is very mall. The simple graffiti count variable is not significant, meaning the number of graffiti calls in a cell does not explain burglary once distance-based measures are included. Overall, the results suggest that proximity to recent graffiti activity is the most useful predictor of burglary risk, more than the total amount of graffiti.\n\n# Part 10: Summary Statistics and Tables\n\n## Exercise 10.1: Model Summary Table\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create nice summary table\nmodel_summary <- broom::tidy(final_model, exponentiate = TRUE) %>%\n  mutate(\n    across(where(is.numeric), ~round(., 3))\n  )\n\nmodel_summary %>%\n  kable(\n    caption   = \"Final Negative Binomial Model Coefficients (Exponentiated)\",\n    col.names = c(\"Variable\", \"Rate Ratio\", \"Std. Error\", \"Z\", \"P-Value\")\n  ) %>%\n  kable_styling(bootstrap_options = c(\"striped\", \"hover\")) %>%\n  footnote(\n    general = \"Rate ratios > 1 indicate positive association with burglary counts.\"\n  )\n```\n\n::: {.cell-output-display}\n`````{=html}\n<table class=\"table table-striped table-hover\" style=\"margin-left: auto; margin-right: auto;border-bottom: 0;\">\n<caption>Final Negative Binomial Model Coefficients (Exponentiated)</caption>\n <thead>\n  <tr>\n   <th style=\"text-align:left;\"> Variable </th>\n   <th style=\"text-align:right;\"> Rate Ratio </th>\n   <th style=\"text-align:right;\"> Std. Error </th>\n   <th style=\"text-align:right;\"> Z </th>\n   <th style=\"text-align:right;\"> P-Value </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:left;\"> (Intercept) </td>\n   <td style=\"text-align:right;\"> 5.261 </td>\n   <td style=\"text-align:right;\"> 0.05 </td>\n   <td style=\"text-align:right;\"> 33.375 </td>\n   <td style=\"text-align:right;\"> 0.000 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> graffiti_n </td>\n   <td style=\"text-align:right;\"> 1.000 </td>\n   <td style=\"text-align:right;\"> 0.00 </td>\n   <td style=\"text-align:right;\"> 1.551 </td>\n   <td style=\"text-align:right;\"> 0.121 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> graffiti_with_units.nn </td>\n   <td style=\"text-align:right;\"> 0.992 </td>\n   <td style=\"text-align:right;\"> 0.00 </td>\n   <td style=\"text-align:right;\"> -17.147 </td>\n   <td style=\"text-align:right;\"> 0.000 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> dist_to_hotspot </td>\n   <td style=\"text-align:right;\"> 1.000 </td>\n   <td style=\"text-align:right;\"> 0.00 </td>\n   <td style=\"text-align:right;\"> 3.343 </td>\n   <td style=\"text-align:right;\"> 0.001 </td>\n  </tr>\n</tbody>\n<tfoot>\n<tr><td style=\"padding: 0; \" colspan=\"100%\"><span style=\"font-style: italic;\">Note: </span></td></tr>\n<tr><td style=\"padding: 0; \" colspan=\"100%\">\n<sup></sup> Rate ratios &gt; 1 indicate positive association with burglary counts.</td></tr>\n</tfoot>\n</table>\n\n`````\n:::\n:::\n\n\n## Exercise 10.2: Key Findings Summary\n\n**Technical Performance:**\n\n-   Cross-validation MAE: 2.81\n-   Model vs. KDE: The KDE baseline performed better than the regression model\n-   Most predictive variable: The nearest-neighbor graffiti distance (graffiti_with_units.nn)\n\nOverall, the model’s technical performance was moderate, as shown by its cross-validation MAE. However, the simple KDE approach still predicted burglaries more accurately than the regression model. While raw 311 graffiti counts were not reliable because some neighborhoods under report issues, the distance to the closest graffiti incidents captured meaningful patterns of physical disorder. Areas located near recent graffiti tended to have higher burglary risk, even if the total number of 311 calls wasn’t a trustworthy measure on its own.\n\n**Spatial Patterns:**\n\nBurglaries in Chicago are not spread out evenly across the city. Instead, they cluster in specific neighborhoods, especially in busy and densely populated areas. The West Side, the Near North and Near West, and parts of the South Side showed the highest concentrations of crime. These areas higher density than the areas with no clusters, with more residential, commercial and foot traffic.\n\nModel residuals were not spatially random, they showed systematic clustering. It consistently underestimated crime in neighborhoods where burglaries were common and overestimated crime in low-crime areas.This is because the model was missing important factors that contribute to how burglary occurs in space. Neighborhood dynamics, such as differences in how often residents report issues to 311, variations in housing density, levels of foot traffic, and other social or environmental conditions were not included in the model. Without these key factors, the model wasn’t able to fully capture the true spatial drivers of burglary, leading to prediction errors. This tell us that burglary is shaped by broader neighborhood conditions.\n\n**Model Limitations:**\n\nThe burglary data was more complicated than what a basic Poisson model could handle. The number of burglaries varies much more across the city than the Poisson model expects, so it can’t accurately represent what’s happening on the ground. Because of that extra variation, we had to use a Negative Binomial model, which is designed to deal with messier, more uneven data.\n\nEven after switching models, the errors still showed strong spatial patterns. Certain parts of the city consistently behaved differently than the model predicted, which suggests that important location-based factors were still missing from the analysis. Things like neighborhood characteristics, population density, foot traffic, and differences in how communities interact with city services all play a role in shaping where burglaries happen. For example, 311 graffiti calls don’t represent the actual amount of graffiti everywhere—they reflect who chooses to report issues. Some neighborhoods trust the 311 system more, expect a quicker response, or are more familiar with the service, while others may under report. As a result, the graffiti data captures differences in civic engagement as much as it captures actual physical disorder. This uneven reporting introduces bias and makes the graffiti variables less reliable as predictors.\n\nAnother challenge is that about 24% of all grid cells had zero burglaries. When so many areas have no incidents at all, it becomes even harder for a statistical model to learn meaningful patterns, because the data is very zero-heavy and uneven.\n\nWhen you combine all of these issues—extra variation in burglary counts, spatial patterns that weren’t explained by the predictors, and the uneven reporting of 311 calls, it becomes clear why the simple KDE baseline performed better. KDE naturally emphasizes clustering and doesn’t rely on strict statistical assumptions, so it ends up capturing the overall spatial pattern of burglaries more effectively than the more complicated regression model.\n\n# Conclusion and Next Steps\n\nThis analysis showed that burglaries in Chicago are highly clustered and that simple spatial smoothing (KDE) can outperform more complex regression models when important neighborhood factors are missing. The regression model struggled with over dispersion, uneven 311 reporting, and many zero-crime areas, all of which made prediction harder.\n\nMoving forward, the model could be improved by adding stronger spatial and social predictors, such as population density, land use, and neighborhood characteristics, and by using disorder measures that aren’t affected by reporting biases.\n",
    "supporting": [
      "Lab3_new_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<script src=\"../../../site_libs/kePrint-0.0.1/kePrint.js\"></script>\n<link href=\"../../../site_libs/lightable-0.0.1/lightable.css\" rel=\"stylesheet\" />\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}